//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetail
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailName { get; set; }
        public string Mobile { get; set; }
        public string NIC { get; set; }
        public string YearOfLeaving { get; set; }
        public string LastClass { get; set; }
        public string Address { get; set; }
        public byte[] ProfilePic { get; set; }
        public string Occupation { get; set; }
        public string ProfessionalQualifications { get; set; }
        public string ActivitiesDuringSchool { get; set; }
        public string AdmissionNumber { get; set; }
        public Nullable<System.DateTime> DateOfAdmission { get; set; }
        public bool Approved { get; set; }
    }
}
