//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomination
    {
        public string UserName { get; set; }
        public string Nomination1 { get; set; }
        public string Nomination2 { get; set; }
        public bool Nomination1AcceptState { get; set; }
        public bool Nomination2AcceptState { get; set; }
        public bool AdminAcceptState { get; set; }
        public bool Approved { get; set; }
    }
}
